### ISSUE TITLE
Resistors for USB-PD support

### ISSUE THREAD

**Issue by Kagee** [Blue-Smoke-Electronics/Ember#167]
Two 5k1 ohm resistors between each CC line and earth will give you 5V@3A from USB-PD-compatible USB-C power supplies. Remember do *not* share the resistor between the two CC lines, as the resistance will be wrong (i.e. like the failure of HW rev 1 of the Rpi 4)

https://hackaday.com/2022/12/06/usb-c-introduction-for-hackers/

**Comment by simenhs** [comment]
Added 5k1 resistors to rev 10. Hacked in resistors on rev9 cards with some thin wires.
