### ISSUE TITLE
Ship units with a silica-bag to prevent condensation

### ISSUE THREAD

**Issue by Kagee** [Blue-Smoke-Electronics/Ember#169]
Ship units with a silica-bag to prevent condensation.

**Comment by simenhs** [comment]
Ordered 1G silica-bags. I will add one to each shipment in the future.

**Comment by simenhs** [comment]
![PXL_20230103_141343066](https://user-images.githubusercontent.com/16391237/210374473-22a73318-301b-4fba-9875-69697167c4af.jpg)
